services:
  postgres_mlflow:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER_MLFLOW}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_MLFLOW}
      POSTGRES_DB: ${POSTGRES_DB_MLFLOW}
    env_file:
      - .env
    volumes:
      - postgres_data_mlflow:/var/lib/postgresql/data
    restart: unless-stopped

  mlflow:
    build:
      context: .
      dockerfile: docker/mlflow/Dockerfile
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER_MLFLOW}:${POSTGRES_PASSWORD_MLFLOW}@postgres_mlflow:5432/${POSTGRES_DB_MLFLOW}
      --host 0.0.0.0
      --port 5000
    env_file:
      - .env
    volumes:
      - ./mlruns:/mlruns
    ports:
      - "5050:5000"
    depends_on:
      - postgres_mlflow
    restart: unless-stopped

volumes:
  postgres_data_mlflow: